In [53]:
import numpy as np
import pandas as pd
import matplotlib as plt

### Array creation and basic properties

In [45]:
# this is how you create a numpy array
a = np.array([1, 2, 3])
b = np.array([[1.5, 2.5], 
              [3.5, 4.5]])

print(a)

# We can print the number of dimensions of a list using the ndim attribute
print(a.ndim)

# shape of array
print(b.shape)

# datatype of array
print(a.dtype)


[1 2 3]
1
(2, 2)
int32


In [19]:
## using the following numpy functions you can create arrays with arbitrary dimensions and fill it up with some initial value
# either ones or zeros
d = np.zeros((2,3))
print(d)

print('-----')

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
-----
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# We can also generate an array with random numbers
rand_array = np.random.rand(3,3)
rand_array

array([[0.82786655, 0.2918201 , 0.94005885],
       [0.48061767, 0.73222301, 0.09676656],
       [0.58486725, 0.47237684, 0.66154953]])

### Array operations

In [24]:
# Arithmetic operators on array apply elementwise.

# Let's create a couple of arrays
a = np.array([10,20,30,40])
b = np.array([1, 2, 3,4])

# Now let's look at a minus b
c = a - b
print(c)

# And let's look at a times b
d = a * b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [30]:
# boolean operation on np arrays
rand_array >= 0.5

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [35]:
# numpy supports matrix manipulation. Let's
# look at matrix product. if we want to do elementwise product, we use the "*" sign
A = np.array([[1,1],
              [0,1]])

B = np.array([[2,0],
              [3,4]])
print('elementwise product:')
print(A*B, '\n')

# if we want to do matrix product, we use the "@" sign or use the dot function
print('matrix multiplication:')
print(A@B, '\n')

elementwise product:
[[2 0]
 [0 4]] 

matrix multiplication:
[[5 4]
 [3 4]] 



#### Some useful array operations for Machine Learning algorithms

In [44]:
# .dot function
# does matrix multiplication on N dim arrays, But on 1D arrays calculates inner product
first = np.array([1, 2.5, 1.25])
second = np.array([5, 2, 4])

## on 1-D arrays
first.dot(second) #inner product: scalar

# on N-D arrays
X = np.array([[2, 4],
              [6, 8],
              [1, 1]])   # 3x2

Y = np.array([[1, 2],
              [3, 4]]) # must be 2xN

print(X.dot(Y))

# now what happens if dimmensions do not match
#Y.dot(X) will throw error
print('------')
#lets fix it using transposition
# X.T is transpose of matrix X
print((Y.T).dot(X.T))



[[14 20]
 [30 44]
 [ 4  6]]
------
[[14 30  4]
 [20 44  6]]


###### <bold>exercise:</bold> add ones along the second axis to a 2x1 array, using numpy functions.

In [52]:
# we use np.c_ function for this purpose
X1 = np.array([[0.], 
               [2.]])
X1_new = np.c_[np.ones((2, 1)), X1]

print('before: \n', X1)
print('after: \n', X1_new)

#will be used in adding bias to the feature vector (don't worry if you didn't understand this now, 
#comeback to this cell after learning about Linear regression)

before: 
 [[0.]
 [2.]]
after: 
 [[1. 0.]
 [1. 2.]]


In [57]:
from PIL import Image, ImageOps
from IPython.display import display

# And let's just look at the image I'm talking about
lecun = Image.open('images/LeCun.jfif')
im = ImageOps.grayscale(lecun)
display(im)

In [61]:
# Now, we can convert this PIL image to a numpy array
array=np.array(im)
print(array.shape)
array

(225, 225)


array([[223, 222, 222, ..., 207, 207, 205],
       [221, 221, 221, ..., 206, 206, 204],
       [218, 218, 218, ..., 205, 205, 203],
       ...,
       [ 69,  68,  67, ...,  91,  98, 107],
       [ 74,  74,  73, ...,  85,  91,  99],
       [ 70,  69,  64, ...,  87,  88,  97]], dtype=uint8)

In [62]:
# Let's create an array the same shape
mask=np.full(array.shape,255)
mask

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]])

In [86]:
# Now let's subtract that from the modified array
modified_array=array-mask
modified_array*=-1

# And as a last step, let's tell numpy to set the value of the datatype correctly
modified_array=modified_array.astype(np.uint8)
modified_array

array([[ 32,  33,  33, ...,  48,  48,  50],
       [ 34,  34,  34, ...,  49,  49,  51],
       [ 37,  37,  37, ...,  50,  50,  52],
       ...,
       [186, 187, 188, ..., 164, 157, 148],
       [181, 181, 182, ..., 170, 164, 156],
       [185, 186, 191, ..., 168, 167, 158]], dtype=uint8)

In [87]:
#convert back to image
display(Image.fromarray(modified_array))

### Slicing, Indexing

In [95]:
#indexing
a = np.array([1, -1, 0])

b = np.array([[1, 3,  5,  7], 
             [1, 12, 13, 14]])
print(a)
print(a[2])
print(b[1,1])

# similar to the standard python lists

[ 1 -1  0]
0
12


In [96]:
#slicing
a = np.array([0,1,2,3,4,5])
print(a[:3])
print(a[2:4])

[0 1 2]
[2 3]


In [102]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[:2], '\n')
print(a[1:3, :1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[1 2 3 4]
 [5 6 7 8]] 

[[5]
 [9]]
